[{"tile": "MN_CottonwoodCo_2010", "error": "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"}, {"tile": "NC_NashCo_2014", "error": "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"}, {"tile": "SD_James_River_NRCS_J_2010", "error": "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"}, {"tile": "TN_Nashville_2011", "error": "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"}, {"tile": "USGS_LPC_FL_PalmBeachCo_2016_LAS_2019", "error": "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"}, {"tile": "USGS_LPC_IN_ET_B6_Blackford_2012_LAS_2016", "error": "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"}, {"error": "Could not create geometry because of errors while reading input."}, {"error": "Could not create geometry because of errors while reading input."}, {"tile": "USGS_LPC_NM_WhiteSands_2015_LAS_2017", "error": "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"}, {"tile": "USGS_LPC_NY_CayugaOswego_TL_2018_LAS_2019", "error": "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"}, {"tile": "USGS_LPC_PA_Dauphin_2016_LAS_2017", "error": "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"}, {"tile": "USGS_LPC_TX_West_Central_B4_2018", "error": "HTTPSConnectionPool(host='s3-us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /usgs-lidar-public/USGS_LPC_TX_West_Central_B4_2018/ept.json (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))"}, {"tile": "USGS_LPC_WA_Western_North_2016_LAS_2018", "error": "Expecting value: line 1 column 1 (char 0)"}, {"tile": "USGS_LPC_WA_Western_South_2016_LAS_2018", "error": "Expecting value: line 1 column 1 (char 0)"}, {"tile": "USGS_Lidar_Point_Cloud_NJ_SdL5_2014_LAS_2015", "error": "HTTPSConnectionPool(host='s3-us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /usgs-lidar-public/USGS_Lidar_Point_Cloud_NJ_SdL5_2014_LAS_2015/ept.json (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))"}, {"tile": "WA_ColumbiaValley_3_2018", "error": "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"}, {"args": ["pdal", "info", "--all", "--driver", "readers.ept", "--readers.ept.resolution=800.0", "--readers.ept.threads=6", "--filters.hexbin.edge_size=1000", "--filters.hexbin.threshold=1", "https://s3-us-west-2.amazonaws.com/usgs-lidar-public/WI_Oshkosh_3Rivers_FondDuLac_TL_2018/ept.json"], "error": "PDAL: readers.ept: Error reading tile: Could not read from s3-us-west-2.amazonaws.com/usgs-lidar-public/WI_Oshkosh_3Rivers_FondDuLac_TL_2018/ept-data/0-0-0-0.laz\n\n"}]